import type { ScheduledSlot, MealPeriod } from '../domain/models';

/**
 * Escapes text according to RFC 5545 section 3.3.11.
 */
function escapeICSValue(value: string): string {
  return value
    .replace(/\\/g, '\\\\')
    .replace(/;/g, '\\;')
    .replace(/,/g, '\\,')
    .replace(/\r?\n/g, '\\n');
}

/**
 * Folds lines longer than 75 octets according to RFC 5545 section 3.1.
 */
function foldICSLine(line: string): string {
  const limit = 75;
  if (line.length <= limit) return line;

  const parts: string[] = [];
  let current = line;

  // First chunk up to 75 chars
  parts.push(current.substring(0, limit));
  current = current.substring(limit);

  // Subsequent folded lines start with a single space and can have up to 74 additional chars
  while (current.length > 0) {
    parts.push(' ' + current.substring(0, limit - 1));
    current = current.substring(limit - 1);
  }

  return parts.join('\r\n');
}

function getPeriodTimes(period: MealPeriod): { startHour: string; startMin: string; endHour: string; endMin: string } {
  switch (period) {
    case 'Breakfast':
      return { startHour: '08', startMin: '00', endHour: '08', endMin: '45' };
    case 'Lunch':
      return { startHour: '12', startMin: '30', endHour: '13', endMin: '30' };
    case 'Dinner':
    default:
      return { startHour: '18', startMin: '30', endHour: '19', endMin: '30' };
  }
}

export function generateICSForSlots(slots: ScheduledSlot[], calendarName = 'DinnerRoll Meal Plan'): string {
  const activeSlots = slots.filter(s => !s.isBlocked && s.mealName);
  const nowUtc = new Date().toISOString().replace(/[-:]/g, '').replace(/\.\d{3}/, '');

  const lines: string[] = [
    'BEGIN:VCALENDAR',
    'VERSION:2.0',
    'PRODID:-//DinnerRoll//Household Meal Scheduler//EN',
    'CALSCALE:GREGORIAN',
    'METHOD:PUBLISH',
    `X-WR-CALNAME:${escapeICSValue(calendarName)}`
  ];

  for (const slot of activeSlots) {
    const rawDate = slot.date.replace(/-/g, '');
    const { startHour, startMin, endHour, endMin } = getPeriodTimes(slot.mealPeriod);
    const dtStart = `${rawDate}T${startHour}${startMin}00`;
    const dtEnd = `${rawDate}T${endHour}${endMin}00`;
    const uid = `${slot.id}-${rawDate}@dinnerroll.local`;

    const titlePrefix = slot.isLeftover ? '[Leftovers] ' : '';
    const summary = `${titlePrefix}${slot.mealName} (${slot.mealPeriod})`;

    let descriptionParts: string[] = [];
    descriptionParts.push(`Meal: ${slot.mealName}`);
    descriptionParts.push(`Period: ${slot.mealPeriod}`);
    if (slot.category) descriptionParts.push(`Category: ${slot.category}`);
    if (slot.isLeftover && slot.originDate) {
      descriptionParts.push(`Type: Leftover (Cooked on ${slot.originDate})`);
    } else {
      descriptionParts.push('Type: Freshly Prepared');
    }

    const macroParts: string[] = [];
    if (slot.calories) macroParts.push(`${slot.calories} kcal`);
    if (slot.protein) macroParts.push(`${slot.protein}g protein`);
    if (slot.fat) macroParts.push(`${slot.fat}g fat`);
    if (slot.carbs) macroParts.push(`${slot.carbs}g carbs`);
    if (macroParts.length > 0) {
      descriptionParts.push(`Nutrition per portion: ${macroParts.join(', ')}`);
    }

    descriptionParts.push('Generated by DinnerRoll');

    const description = descriptionParts.join('\n');

    lines.push('BEGIN:VEVENT');
    lines.push(`UID:${uid}`);
    lines.push(`DTSTAMP:${nowUtc}`);
    lines.push(`DTSTART:${dtStart}`);
    lines.push(`DTEND:${dtEnd}`);
    lines.push(`SUMMARY:${escapeICSValue(summary)}`);
    lines.push(`DESCRIPTION:${escapeICSValue(description)}`);
    if (slot.category) {
      lines.push(`CATEGORIES:${escapeICSValue(slot.category)}`);
    }
    lines.push('STATUS:CONFIRMED');
    lines.push('END:VEVENT');
  }

  lines.push('END:VCALENDAR');

  return lines.map(foldICSLine).join('\r\n') + '\r\n';
}

export function downloadICSFile(slots: ScheduledSlot[], filename = 'dinnerroll-plan.ics'): void {
  const icsData = generateICSForSlots(slots);
  const blob = new Blob([icsData], { type: 'text/calendar;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.setAttribute('download', filename);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
